POST http://localhost:8080/api/v1/trip-requests
Content-Type: application/json

{
  "touristId": "11112111-9111-1111-1111-111111111111",
  "pickupDescription": "Bhubaneswar Airport",
  "pickupLatitude": 20.2444,
  "pickupLongitude": 85.8178,
  "stops": [],
  "destinationDescription": "Puri",
  "destinationLatitude": 19.8135,
  "destinationLongitude": 85.8312,
  "startDate": "2026-08-27",
  "endDate": "2026-08-27",
  "passengerCount": 4,
  "tripBrief": "Airport to Puri"
}